- name: Update latest packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install required repos
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.name }}"
    gpgkey: "{{ item.gpgkey }}"
  loop:
    - { name: "Atom-Editor", baseurl: "https://packagecloud.io/AtomEditor/atom/el/7/$basearch", gpgkey: "https://packagecloud.io/AtomEditor/atom/gpgkey" }
    - { name: "Google-Chrome", baseurl: "http://dl.google.com/linux/chrome/rpm/stable/$basearch", gpgkey: "https://dl-ssl.google.com/linux/linux_signing_key.pub" }
    - { name: "Fortinet-Client", baseurl: "https://repo.fortinet.com/repo/centos/7/os/x86_64", gpgkey: "https://repo.fortinet.com/repo/centos/7/os/x86_64/RPM-GPG-KEY" }



- name: Install common packages
  dnf:
    update_cache: yes
    name:
      - konsole
      - git
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - ca-certificates
      - curl
      - gnome-tweaks
      - gnome-shell-extension-common
      - python3-psutil
      - google-chrome-stable
      - atom
      - forticlient
      - vim
      - wget
      - make
      - gcc
      - lastpass-cli
      - unzip

- name: Install fedora only packages
  block:
    - name: Install docker repos
      yum_repository:
        name: "{{ item.name }}"
        baseurl: "{{ item.baseurl }}"
        description: "{{ item.name }}"
        gpgkey: "{{ item.gpgkey }}"
      loop:
        - { name: "docker-ce-stable", baseurl: "https://download.docker.com/linux/fedora/31//$basearch/stable", gpgkey: "https://download.docker.com/linux/fedora/gpg" } 
      when: ansible_distribution == 'Fedora'

    - name: Install fedora only packages
      dnf:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - zeal
