- name: Update latest packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install required repo keys
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id | default(omit)}}"
  loop:
    - { url: "https://dl.google.com/linux/linux_signing_key.pub" }
    - { url: "https://download.docker.com/linux/ubuntu/gpg", id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 }
    - { url: "https://repo.fortinet.com/repo/ubuntu/DEB-GPG-KEY" }
    - { url: "https://packagecloud.io/AtomEditor/atom/gpgkey" }

- name: Install required repos
  apt_repository:
    repo: "{{ item.repo }}"
  loop:
    - { repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" }
    - { repo: "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" }
    - { repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" }
    - { repo: "deb [arch=amd64] https://repo.fortinet.com/repo/ubuntu/ xenial multiverse" }

- name: Install common packages
  apt:
    update_cache: yes
    pkg:
      - konsole
      - git
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - gnome-tweaks
      - gnome-shell-extensions
      - zeal
      - python-psutil
      - google-chrome-stable
      - atom
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - forticlient
      - vim
      - wget
      - python-pip

- name: Install non repo packages
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.2-amd64.deb"
  ignore_errors: yes
