---
- name: Gather facts as playbook executor
  setup:
  become: no

- name: Ensure themes directory exists
  file:
    path: "{{ ansible_env.HOME }}/.themes"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Download Prof Light DS theme
  git:
    repo: "https://github.com/paullinuxthemer/Prof-Gnome.git"
    dest: /tmp/Prof-Gnome

- name: Move theme into themes dir
  copy:
    src: /tmp/Prof-Gnome/Prof-Gnome-Light-DS-3.5
    dest: "{{ ansible_env.HOME }}/.themes/"
    remote_src: yes
  register: prof_theme

- name: Download background image
  get_url:
    url: http://getwallpapers.com/wallpaper/full/9/9/f/14529.jpg
    dest: "{{ ansible_env.HOME }}/Documents/wallpaper.jpg"
  register: background_image
  become: no

- name: Install Paper icons (Ubuntu)
  block:
    - name: Install Paper icons repo
      apt_repository:
        repo: ppa:snwh/ppa

    - name: Install Paper icons
      apt:
        pkg: paper-icon-theme
  when: ansible_distribution == 'Ubuntu'

- name: Install Paper icons (RHEL)
  block:
    - name: Install Paper icons
      dnf:
        name: https://download.opensuse.org/repositories/home:/snwh:/paper/Fedora_25/noarch/paper-icon-theme-1.3.git+1475704478.00b1750-9.1.noarch.rpm
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Paper icons (Fedora)
  dnf:
    name: paper-icon-theme
  when: ansible_distribution == "Fedora'

- name: Ensure extensions directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions/"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0775

- name: Install extensions
  gnome_shell_extension:
    id: "{{ item }}"
    gnome_extension_path: "{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions/"
  loop:
    - 28
    - 1160
    - 19
  become: no

- name: Set gnome settings
  become: no
  block:
    - name: Set background image
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file://{{ ansible_env.HOME }}/Documents/wallpaper.jpg'"

    - name: Set dock favorites
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.kde.konsole.desktop', 'slack_slack.desktop', 'atom_atom.desktop', 'zeal.desktop', 'org.gnome.tweaks.desktop']"

    - name: Change caps to ctrl
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:ctrl_modifier']"

    - name: Show battery percentage
      dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"

    - name: Set paper-icons
      dconf:
        key: "/org/gnome/desktop/interface/{{ item }}"
        value: "'Paper'"
      loop:
        - icon-theme
        - cursor-theme

    - name: Set Prof Light theme
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'{{ prof_theme.dest | basename }}'"
